---
deployment:
  tasks:
    # Set deployment paths for frontend and backend
    - export BACKEND_PATH=/home/ijerucyz/erpbackend.ijernd.com
    - export FRONTEND_PATH=/home/ijerucyz/erpfrontend.ijernd.com

    # Optional: include hidden files like .htaccess, .env, etc.
    - shopt -s dotglob

    # Deploy backend
    - echo "Deploying backend..."
    - cp -r ./backend/* $BACKEND_PATH

    # Deploy frontend
    - echo "Deploying frontend..."
    - cp -r ./frontend/build/* $FRONTEND_PATH
